(PA-8250) Support nightly 8 to 9 upgrades
When upgrading from one collection to another on deb/rpm platforms, we try to
remove the release package for the old collection. However, the name was
harcoded to `puppet${major}-release`, so upgrading from puppet*-nightly-release
to anything else failed:

    # rpm -e puppet8-release
    error: package puppet8-release is not installed

Now query for the name of the release package to erase/purge, which will work
for final and nightly rpm release packages:

    # rpm -qa --qf '%{NAME}\n' | grep "^puppet${major}.*-release$" | head -1
    puppet8-nightly-release

Same for deb:

    # dpkg-query -W -f='${Package}\n' 2>/dev/null | grep "^puppet${major}.*-release$" | head -1
    puppet8-nightly-release

It is assumed only one release package for a given collection is installed, so
you can't have puppet8-release and puppet8-nightly-release both installed, and
try to upgrade to puppet9-nightly-release.